### ISSUE TITLE
Network Bandwidth and Storage Too Low in the free Tier

### ISSUE THREAD

**Issue by devarshishimpi** [domcloud/domcloud#23]
Hi,

Recently was trying out Domcloud after the issue with Heroku.
Before shifting from Heroku, I found a few issues with the load.

Hitting the 1 GB bandwidth CAP can be done just with a few visitors, approx 100-1000, and due to other asset files, it might hit the Bandwidth CAP even earlier.

Also, the Storage Capacity faces the same issue, preferably raise that to 5GB so that it can be used and the Bandwidth CAP to 20GB?.

Apart from that loved your work and keep it up!!!

Thanks.

**Comment by willnode** [comment]
I think what I give about bandwidth and storage is enough to cover basic usage -- very basic usage.

Bandwidths can be saved if done correctly. For instance, a returning user should simply see a static file as 304. This doesn't work if you put large static files there (like video), which with reasonable people, should really think of an alternative solution like S3. If we give people a lot of bandwidth it's not the network bill I worry about, it's the CPU.

Storage has the same kind of story. There are legit use cases where just with code alone, can hit the 1GB limit easily. Think about `node_modules`. 1 GB is already huge, even services that are "free" but use cloud functions like Lambda or Vercel wouldn't serve your website if it's more than 256 MB.

This is still an open question though, that's why this service is "beta", nothing happens when you hit the limit currently. Our current focus is to grab a lot of people's attention until it has enough paid users and covers up our hosting costs.

**Comment by devarshishimpi** [comment]
Hi,

I didn't mean large static files like video files on the website, not even images. There are solutions for it as you mentioned like s3 or even cloudinary or others. Files without them like a simple React project or any stack web app would contain lots of CSS and JS files which would hit the bandwidth faster.

Regarding the Bandwidth it's nowhere to Vercel or similar, I understand it's still the free plan so at least 20GB for bandwidth should be enough??

For Storage, We never upload the `node_modules` folder in the standard way 😄 and even without that, Storage has great issues. Lambda and Vercel depend on Git Repos which have rarely a standard 5GB ( for Github ) and 10GB ( for Gitlab ), which varies cloud to cloud, so the point of 256 MB wouldn't be valid.

Anyways great project!! and Good luck with it. Hope you understand the needs for the free plan as well as other plans. They at least need to be half of the cloud providers out there, even the Pricing is highly priced.

Thanks.

**Comment by willnode** [comment]
Okay, I agree the current limit may not be practical enough for some users, but let's see anyway. Currently, almost all free users don't overpass their storage or bandwidth limit. 

I try to just be rational and not overpromising. But if currently paid subscribers already overpassing the hosting costs I will happily increase the official free limit anyway, haha. Spread the word!

**Comment by devarshishimpi** [comment]
Ah True. Still testing different packages and performance before shifting. Looks Good to me till now apart from the fact that it's new and not established.

Paid users would grow after the pricing would be affordable. People are currently looking for alternatives to Heroku and you might want to compete Render and Railway, similar services. I understand even you have been priced and paying for the digital ocean droplets but We would shift to paid users only if it's affordable right??? There are many out there which are cheaper and more established.

Don't take me negatively there, I just simply mean it doesn't compete with other Cloud Providers. You'll recover the price soon even though the pricing would be a bit more cheaper as you would gain paid users.

**Comment by willnode** [comment]
OK after more examination this measure is close to being final:

```
Free -> 1.5GB storage, 2GB network
1.5$ -> 3GB storage, 20GB network
5$ -> 10GB storage, 100GB network
15$ -> 30GB storage, 500GB network
```

Our busiest website (3 years subscribers since early times) doesn't even cross 5GB storage or 10GB network. I'm pretty sure that this is realistic as far as I can offer. It's cheaper than managing a cloud VM on your own.
